fun main(args: Array<String>)
{
    println("Enter an integer between 1-10: ");
    var num = Integer.valueOf(readLine())

    if(num == 1)
        println("I")
    if(num == 2)
        println("II")
    if (num == 3)
        println("III")
    if (num == 4)
        println("IV")
    if (num == 5)
        println("V")
    if (num == 6)
        println("VI")
    if (num == 7)
        println("VII")
    if (num == 8)
        println("VIII")
    if (num == 9)
        println("IX")
    if (num == 10)
        println("X")
    if (num > 10)
        println("Error.")
    if (num < 1)
        println("Error.")

}